[package]
name = "mix-explain"
version.workspace = true
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[dependencies]
mix-core = { path = "../core" }
mix-events = { path = "../events" }
mix-ui = { path = "../ui" }

[dev-dependencies]
divan = { workspace = true }
mix-nixgen = { path = "../nixgen" }
mix-shell = { path = "../shell" }

[[bench]]
name = "explain"
harness = false

[lints]
workspace = true
