[package]
name = "mix-render"
version.workspace = true
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[dependencies]
mix-events = { path = "../events" }
mix-explain = { path = "../explain" }
mix-ui = { path = "../ui" }
pbjson-types = "0.9.0"
serde_json = { workspace = true }

[dev-dependencies]
mix-core = { path = "../core" }
tempfile = { workspace = true }

[lints]
workspace = true
