[package]
name = "mix-shell"
version.workspace = true
edition = "2024"
build = "build.rs"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[features]
default = []
embed-tarball = []
machine-tests = []

[dependencies]
uuid = { version = "1.26.1", features = ["v7"] }
mix-core = { path = "../core" }
mix-events = { path = "../events" }
mix-exec = { path = "../exec" }
mix-nixgen = { path = "../nixgen" }
mix-pins = { path = "../pins" }
futures-util = { workspace = true }
liblzma = { version = "0.4.8", default-features = false, features = ["static"] }
nix = { workspace = true }
rustix = { version = "1.1.4", features = ["fs"] }
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "http2"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11.0"
tar = "0.4.46"
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }

[build-dependencies]
mix-pins = { path = "../pins" }
sha2 = "0.11.0"

[dev-dependencies]
divan = { workspace = true }
mix-core = { path = "../core", features = ["world"] }
mockito = "=1.7.2"
proptest = { workspace = true }

[[bench]]
name = "output"
harness = false

[[bench]]
name = "tarball"
harness = false

[[bench]]
name = "target"
harness = false

[[test]]
name = "machine"
required-features = ["machine-tests"]

[lints]
workspace = true
