use crate::GENERATED_HEADER;
use crate::escape::{NulByte, nix_string_literal};

#[derive(Debug)]
pub struct FlakeConfig {
    system: String,
    username: String,
    nixpkgs_rev: &'static str,
    home_manager_rev: &'static str,
}

impl FlakeConfig {
    pub fn new(
        system: &str,
        username: &str,
        nixpkgs_rev: &'static str,
        home_manager_rev: &'static str,
    ) -> Result<Self, NulByte> {
        Ok(Self {
            system: nix_string_literal(system)?,
            username: nix_string_literal(username)?,
            nixpkgs_rev,
            home_manager_rev,
        })
    }

    pub fn render(&self) -> String {
        let Self {
            system,
            username,
            nixpkgs_rev,
            home_manager_rev,
        } = self;
        format!(
            "{GENERATED_HEADER}\
{{
  description = \"Generated by mix\";

  inputs = {{
    nixpkgs.url = \"github:NixOS/nixpkgs/{nixpkgs_rev}\";
    home-manager = {{
      url = \"github:nix-community/home-manager/{home_manager_rev}\";
      inputs.nixpkgs.follows = \"nixpkgs\";
    }};
  }};

  outputs = {{ nixpkgs, home-manager, ... }}:
    let
      system = {system};
      pkgs = nixpkgs.legacyPackages.${{system}};
    in {{
      homeConfigurations.{username} = home-manager.lib.homeManagerConfiguration {{
        inherit pkgs;
        modules = [ ./home.nix ];
      }};
    }};
}}
"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const NIXPKGS_REV: &str = "efe6f071ede9d21c37462d2d6682d5e670099684";
    const HOME_MANAGER_REV: &str = "efa3ccb4c3cc90d832eab232976379058fa75aa3";

    #[test]
    fn renders_the_generated_header() {
        assert!(
            FlakeConfig::new("x86_64-linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV)
                .unwrap()
                .render()
                .starts_with(GENERATED_HEADER)
        );
    }

    #[test]
    fn renders_the_system_as_a_let_bound_string() {
        let rendered = FlakeConfig::new("x86_64-linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV)
            .unwrap()
            .render();
        assert!(rendered.contains("system = \"x86_64-linux\";"));
        assert!(rendered.contains("nixpkgs.legacyPackages.${system}"));
    }

    #[test]
    fn renders_the_username_as_a_quoted_home_configuration_key() {
        let rendered = FlakeConfig::new("x86_64-linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV)
            .unwrap()
            .render();
        assert!(
            rendered.contains(
                "homeConfigurations.\"mix\" = home-manager.lib.homeManagerConfiguration {"
            )
        );
    }

    #[test]
    fn references_home_nix_as_a_module_path() {
        let rendered = FlakeConfig::new("x86_64-linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV)
            .unwrap()
            .render();
        assert!(rendered.contains("modules = [ ./home.nix ];"));
    }

    #[test]
    fn renders_the_pinned_nixpkgs_and_home_manager_revisions() {
        let rendered = FlakeConfig::new("x86_64-linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV)
            .unwrap()
            .render();
        assert!(rendered.contains(&format!("github:NixOS/nixpkgs/{NIXPKGS_REV}")));
        assert!(rendered.contains(&format!(
            "github:nix-community/home-manager/{HOME_MANAGER_REV}"
        )));
    }

    #[test]
    fn rejects_a_null_byte_in_the_system_string() {
        assert!(FlakeConfig::new("x86_64\0linux", "mix", NIXPKGS_REV, HOME_MANAGER_REV).is_err());
    }

    #[test]
    fn rejects_a_null_byte_in_the_username() {
        assert!(FlakeConfig::new("x86_64-linux", "mi\0x", NIXPKGS_REV, HOME_MANAGER_REV).is_err());
    }

    #[test]
    fn escapes_a_quote_in_the_username_instead_of_breaking_out_of_the_key() {
        let rendered = FlakeConfig::new("x86_64-linux", "mi\"x", NIXPKGS_REV, HOME_MANAGER_REV)
            .unwrap()
            .render();
        assert!(rendered.contains("homeConfigurations.\"mi\\\"x\""));
    }
}
