use crate::ast::{Key, RelPath, Verbatim};
use crate::ident::Ident;
use crate::print::Writer;

const HOME_MANAGER: Ident = Ident::new_static("home-manager");
const NIXPKGS: Ident = Ident::new_static("nixpkgs");
const HOME_NIX: RelPath = RelPath::new_static("home.nix");

static HOME_MANAGER_KEY: Key = Key::new_static("home-manager");
static NIXPKGS_KEY: Key = Key::new_static("nixpkgs");
static DESCRIPTION: Key = Key::new_static("description");
static INPUTS: Key = Key::new_static("inputs");
static OUTPUTS: Key = Key::new_static("outputs");
static FOLLOWS: Key = Key::new_static("follows");
static URL: Key = Key::new_static("url");
static HOME_CONFIGURATIONS: Key = Key::new_static("homeConfigurations");
static LIB: Key = Key::new_static("lib");
static HOME_MANAGER_CONFIGURATION: Key = Key::new_static("homeManagerConfiguration");
static MODULES: Key = Key::new_static("modules");
static PKGS: Key = Key::new_static("pkgs");
static LEGACY_PACKAGES: Key = Key::new_static("legacyPackages");

const GENERATED_BY_MIX: Verbatim<'static> = Verbatim::new_static("Generated by mix");
const HOME_MANAGER_URL: Verbatim<'static> =
    Verbatim::new_static("github:nix-community/home-manager/");
const NIXPKGS_URL: Verbatim<'static> = Verbatim::new_static("github:NixOS/nixpkgs/");
const NIXPKGS_TEXT: Verbatim<'static> = Verbatim::new_static("nixpkgs");

pub(crate) fn write_flake<'k>(
    w: &mut Writer<'_>,
    username: &'k Key,
    system: &'k Key,
    nixpkgs_rev: Verbatim<'_>,
    home_manager_rev: Verbatim<'_>,
) {
    w.attrs(|a| {
        a.entry(&DESCRIPTION, |w| w.string(|s| s.verbatim(GENERATED_BY_MIX)));
        a.entry(&INPUTS, |w| {
            w.attrs(|a| {
                a.entry(&HOME_MANAGER_KEY, |w| {
                    w.attrs(|a| {
                        a.entry(&INPUTS, |w| {
                            w.attrs(|a| {
                                a.entry(&NIXPKGS_KEY, |w| {
                                    w.attrs(|a| {
                                        a.entry(&FOLLOWS, |w| {
                                            w.string(|s| s.verbatim(NIXPKGS_TEXT))
                                        })
                                    })
                                })
                            })
                        });
                        a.entry(&URL, |w| {
                            w.string(|s| {
                                s.verbatim(HOME_MANAGER_URL);
                                s.verbatim(home_manager_rev);
                            })
                        });
                    })
                });
                a.entry(&NIXPKGS_KEY, |w| {
                    w.attrs(|a| {
                        a.entry(&URL, |w| {
                            w.string(|s| {
                                s.verbatim(NIXPKGS_URL);
                                s.verbatim(nixpkgs_rev);
                            })
                        })
                    })
                });
            })
        });
        a.entry(&OUTPUTS, |w| {
            w.lambda([&HOME_MANAGER, &NIXPKGS], true, |w| {
                w.attrs(|a| {
                    a.entry(&HOME_CONFIGURATIONS, |w| {
                        w.attrs(|a| {
                            a.entry(username, |w| {
                                w.apply(
                                    |w| {
                                        w.var(&HOME_MANAGER);
                                        w.keys([&LIB, &HOME_MANAGER_CONFIGURATION]);
                                    },
                                    |w| {
                                        w.attrs(|a| {
                                            a.entry(&MODULES, |w| {
                                                w.list(|l| l.item(|w| w.path(&HOME_NIX)))
                                            });
                                            a.entry(&PKGS, |w| {
                                                w.var(&NIXPKGS);
                                                w.keys([&LEGACY_PACKAGES, system]);
                                            });
                                        })
                                    },
                                )
                            })
                        })
                    })
                })
            })
        });
    });
}
