use crate::ast::{Key, RelPath, Verbatim};
use crate::inputs::{INPUTS, Input, Pin, Pins};
use crate::print::Writer;

const HOME_NIX: RelPath = RelPath::new_static("home.nix");

static DESCRIPTION: Key = Key::new_static("description");
static INPUTS_KEY: Key = Key::new_static("inputs");
static OUTPUTS: Key = Key::new_static("outputs");
static FOLLOWS: Key = Key::new_static("follows");
static URL: Key = Key::new_static("url");
static HOME_CONFIGURATIONS: Key = Key::new_static("homeConfigurations");
static LIB: Key = Key::new_static("lib");
static HOME_MANAGER_CONFIGURATION: Key = Key::new_static("homeManagerConfiguration");
static MODULES: Key = Key::new_static("modules");
static PKGS: Key = Key::new_static("pkgs");
static LEGACY_PACKAGES: Key = Key::new_static("legacyPackages");

const GENERATED_BY_MIX: Verbatim<'static> = Verbatim::new_static("Generated by mix");
const GITHUB: Verbatim<'static> = Verbatim::new_static("github:");
const SLASH: Verbatim<'static> = Verbatim::new_static("/");

pub(crate) fn write_flake<'k>(
    w: &mut Writer<'_>,
    username: &'k Key,
    system: &'k Key,
    revs: Pins<Verbatim<'_>>,
) {
    w.attrs(|a| {
        a.entry(&DESCRIPTION, |w| w.string(|s| s.verbatim(GENERATED_BY_MIX)));
        a.entry(&INPUTS_KEY, |w| {
            w.attrs(|a| {
                for input in &INPUTS {
                    a.entry(&input.key, |w| {
                        w.attrs(|a| {
                            if let Some(follows) = input.follows {
                                let followed = INPUTS
                                    .iter()
                                    .find(|other| other.name == follows)
                                    .expect("checked when the table is built");
                                a.entry(&INPUTS_KEY, |w| {
                                    w.attrs(|a| {
                                        a.entry(&followed.key, |w| {
                                            w.attrs(|a| {
                                                a.entry(&FOLLOWS, |w| {
                                                    w.string(|s| {
                                                        s.verbatim(Verbatim::new_static(follows))
                                                    })
                                                })
                                            })
                                        })
                                    })
                                });
                            }
                            a.entry(&URL, |w| {
                                w.string(|s| {
                                    s.verbatim(GITHUB);
                                    s.verbatim(Verbatim::new_static(input.owner));
                                    s.verbatim(SLASH);
                                    s.verbatim(Verbatim::new_static(input.repo));
                                    s.verbatim(SLASH);
                                    s.verbatim(revs.of(input.pin));
                                })
                            });
                        })
                    });
                }
            })
        });
        a.entry(&OUTPUTS, |w| {
            w.lambda(INPUTS.iter().map(|input| &input.ident), true, |w| {
                w.attrs(|a| {
                    a.entry(&HOME_CONFIGURATIONS, |w| {
                        w.attrs(|a| {
                            a.entry(username, |w| {
                                w.apply(
                                    |w| {
                                        w.var(&input(Pin::HomeManager).ident);
                                        w.keys([&LIB, &HOME_MANAGER_CONFIGURATION]);
                                    },
                                    |w| {
                                        w.attrs(|a| {
                                            a.entry(&MODULES, |w| {
                                                w.list(|l| l.item(|w| w.path(&HOME_NIX)))
                                            });
                                            a.entry(&PKGS, |w| {
                                                w.var(&input(Pin::Nixpkgs).ident);
                                                w.keys([&LEGACY_PACKAGES, system]);
                                            });
                                        })
                                    },
                                )
                            })
                        })
                    })
                })
            })
        });
    });
}

fn input(pin: Pin) -> &'static Input {
    INPUTS
        .iter()
        .find(|input| input.pin == pin)
        .expect("every pin has an input")
}
