use std::collections::BTreeSet;

use crate::GENERATED_HEADER;
use crate::ast::{Expr, Key, NixStr, RelPath, StrPart};
use crate::escape::NulByte;
use crate::ident::Ident;
use crate::print;

const HOME_MANAGER: Ident = Ident::new_static("home-manager");
const NIXPKGS: Ident = Ident::new_static("nixpkgs");
const HOME_NIX: RelPath = RelPath::new_static("home.nix");

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum System {
    X86_64Linux,
    Aarch64Linux,
    X86_64Darwin,
    Aarch64Darwin,
}

impl System {
    pub const fn as_str(self) -> &'static str {
        match self {
            System::X86_64Linux => "x86_64-linux",
            System::Aarch64Linux => "aarch64-linux",
            System::X86_64Darwin => "x86_64-darwin",
            System::Aarch64Darwin => "aarch64-darwin",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rev(&'static str);

impl Rev {
    pub const fn new_static(s: &'static str) -> Self {
        assert!(is_rev(s.as_bytes()), "not a 40 character git revision");
        Self(s)
    }

    pub fn as_str(self) -> &'static str {
        self.0
    }
}

const fn is_rev(bytes: &[u8]) -> bool {
    if bytes.len() != 40 {
        return false;
    }
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        if !(b.is_ascii_digit() || (b >= b'a' && b <= b'f')) {
            return false;
        }
        i += 1;
    }
    true
}

impl From<Rev> for NixStr {
    fn from(rev: Rev) -> Self {
        NixStr::from_checked(rev.0)
    }
}

#[derive(Debug)]
pub struct FlakeConfig {
    expr: Expr,
}

impl FlakeConfig {
    pub fn new(
        system: System,
        username: &str,
        nixpkgs_rev: Rev,
        home_manager_rev: Rev,
    ) -> Result<Self, NulByte> {
        Ok(Self {
            expr: flake(system, Key::new(username)?, nixpkgs_rev, home_manager_rev),
        })
    }

    pub fn render(&self) -> String {
        let mut out = String::with_capacity(GENERATED_HEADER.len() + 1024);
        out.push_str(GENERATED_HEADER);
        print::print_into(&self.expr, &mut out);
        out.push('\n');
        out
    }
}

fn flake(system: System, username: Key, nixpkgs_rev: Rev, home_manager_rev: Rev) -> Expr {
    let url = |prefix: &'static str, rev: Rev| {
        Expr::Str(vec![
            StrPart::Lit(NixStr::new_static(prefix)),
            StrPart::Lit(NixStr::from(rev)),
        ])
    };
    let inputs = Expr::attrs([
        (
            Key::from(&HOME_MANAGER),
            Expr::attrs([
                (
                    Key::new_static("inputs"),
                    Expr::attrs([(
                        Key::from(&NIXPKGS),
                        Expr::attrs([(
                            Key::new_static("follows"),
                            Expr::Str(vec![StrPart::Lit(NixStr::new_static("nixpkgs"))]),
                        )]),
                    )]),
                ),
                (
                    Key::new_static("url"),
                    url("github:nix-community/home-manager/", home_manager_rev),
                ),
            ]),
        ),
        (
            Key::from(&NIXPKGS),
            Expr::attrs([(
                Key::new_static("url"),
                url("github:NixOS/nixpkgs/", nixpkgs_rev),
            )]),
        ),
    ]);
    let configuration = Expr::apply(
        Expr::select(
            Expr::Var(HOME_MANAGER),
            Key::new_static("lib"),
            [Key::new_static("homeManagerConfiguration")],
        ),
        Expr::attrs([
            (
                Key::new_static("modules"),
                Expr::List(vec![Expr::Path(HOME_NIX)]),
            ),
            (
                Key::new_static("pkgs"),
                Expr::select(
                    Expr::Var(NIXPKGS),
                    Key::new_static("legacyPackages"),
                    [Key::new_static(system.as_str())],
                ),
            ),
        ]),
    );
    let outputs = Expr::Lambda {
        formals: BTreeSet::from([HOME_MANAGER, NIXPKGS]),
        ellipsis: true,
        body: Box::new(Expr::attrs([(
            Key::new_static("homeConfigurations"),
            Expr::attrs([(username, configuration)]),
        )])),
    };
    Expr::attrs([
        (
            Key::new_static("description"),
            Expr::Str(vec![StrPart::Lit(NixStr::new_static("Generated by mix"))]),
        ),
        (Key::new_static("inputs"), inputs),
        (Key::new_static("outputs"), outputs),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    use mix_pins::{HOME_MANAGER_REV, NIXPKGS_REV};

    const NIXPKGS_PIN: Rev = Rev::new_static(NIXPKGS_REV);
    const HOME_MANAGER_PIN: Rev = Rev::new_static(HOME_MANAGER_REV);

    fn render(username: &str) -> String {
        FlakeConfig::new(System::X86_64Linux, username, NIXPKGS_PIN, HOME_MANAGER_PIN)
            .unwrap()
            .render()
    }

    #[test]
    fn renders_the_generated_header() {
        assert!(render("mix").starts_with(GENERATED_HEADER));
    }

    #[test]
    fn selects_the_packages_of_the_system() {
        assert!(render("mix").contains("pkgs = nixpkgs.legacyPackages.x86_64-linux;"));
    }

    #[test]
    fn renders_the_username_as_a_home_configuration_key() {
        assert!(render("mix").contains(
            "    homeConfigurations = {\n      mix = home-manager.lib.homeManagerConfiguration {"
        ));
    }

    #[test]
    fn quotes_a_username_that_is_not_an_identifier() {
        assert!(render("john.doe").contains("\"john.doe\" = home-manager.lib"));
        assert!(render("mi\"x").contains("\"mi\\\"x\" = home-manager.lib"));
    }

    #[test]
    fn references_home_nix_as_a_module_path() {
        assert!(render("mix").contains("modules = [\n          ./home.nix\n        ];"));
    }

    #[test]
    fn renders_the_pinned_nixpkgs_and_home_manager_revisions() {
        let rendered = render("mix");
        assert!(rendered.contains(&format!("url = \"github:NixOS/nixpkgs/{NIXPKGS_REV}\";")));
        assert!(rendered.contains(&format!(
            "url = \"github:nix-community/home-manager/{HOME_MANAGER_REV}\";"
        )));
        assert!(rendered.contains("follows = \"nixpkgs\";"));
    }

    #[test]
    fn rejects_a_null_byte_in_the_username() {
        assert!(
            FlakeConfig::new(System::X86_64Linux, "mi\0x", NIXPKGS_PIN, HOME_MANAGER_PIN).is_err()
        );
    }

    #[test]
    fn names_every_system_nix_knows() {
        assert_eq!(System::X86_64Linux.as_str(), "x86_64-linux");
        assert_eq!(System::Aarch64Linux.as_str(), "aarch64-linux");
        assert_eq!(System::X86_64Darwin.as_str(), "x86_64-darwin");
        assert_eq!(System::Aarch64Darwin.as_str(), "aarch64-darwin");
    }
}
