pub mod ast;
mod escape;
mod flake;
mod home;
mod ident;
mod installable;
pub mod lock;
mod print;

pub(crate) const GENERATED_HEADER: &str = "\
# Code generated by mix. DO NOT EDIT.
# Manual changes will be overwritten. Use `mix` commands to manage this configuration.

";

pub use escape::NulByte;
pub use flake::{FlakeConfig, Rev, System};
pub use home::{CopyIntoGeneration, HomeModule, InvalidInput, StateVersion};
pub use ident::{FileName, Ident, InvalidIdent, is_identifier};
pub use installable::{AttrPath, FlakeRef, Installable, InvalidInstallable, PublicKey};
