mod builder;
mod escape;
mod flake;
mod ident;
mod value;

pub(crate) const GENERATED_HEADER: &str = "\
# Code generated by mix. DO NOT EDIT.
# Manual changes will be overwritten. Use `mix` commands to manage this configuration.

";

pub use builder::{HomeManagerConfig, InvalidInput};
pub use flake::FlakeConfig;
