[package]
name = "mix-cli"
version.workspace = true
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"
default-run = "mix"

[[bin]]
name = "mix"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive", "env"] }
mix-events = { path = "../events" }
mix-render = { path = "../render" }
mix-rpc = { path = "../rpc" }
nix = { workspace = true, features = ["signal"] }
tokio = { workspace = true, features = ["signal"] }
uuid = { version = "1.26.1", features = ["v7"] }

[dev-dependencies]
mix-core = { path = "../core" }
mix-exec = { path = "../exec" }
mix-shell = { path = "../shell" }
tempfile = { workspace = true }

[lints]
workspace = true
