[package]
name = "mix-cli"
version = "0.1.0"
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[features]
embed-tarball = ["mix-app/embed-tarball"]

[dependencies]
mix-app = { path = "../app" }
mix-core = { path = "../core" }
mix-ui = { path = "../ui" }
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive", "env"] }
