[package]
name = "mix-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mix"
path = "src/main.rs"

[dependencies]
mix-bootstrap = { path = "../bootstrap" }
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
tokio = { workspace = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
