# Code generated by mix. DO NOT EDIT.
# Manual changes will be overwritten. Use `mix` commands to manage this configuration.

{
  description = "Generated by mix";
  inputs = {
    home-manager = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:nix-community/home-manager/efa3ccb4c3cc90d832eab232976379058fa75aa3";
    };
    nixpkgs = {
      url = "github:NixOS/nixpkgs/efe6f071ede9d21c37462d2d6682d5e670099684";
    };
  };
  outputs = { home-manager, nixpkgs, ... }: {
    homeConfigurations = {
      mix = home-manager.lib.homeManagerConfiguration {
        modules = [
          ./home.nix
        ];
        pkgs = nixpkgs.legacyPackages.x86_64-linux;
      };
    };
  };
}
