[package]
name = "mix-events"
version = "0.1.0"
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[dependencies]
pbjson = "0.9.0"
pbjson-types = "0.9.0"
prost = "0.14.4"
serde = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
pbjson-build = "0.9.0"
prost-build = "0.14.4"
protox = "0.9.1"

[dev-dependencies]
proptest = { workspace = true }
serde_json = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["pbjson", "pbjson-types", "serde"]
