[package]
name = "mix-rpc"
version.workspace = true
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[dependencies]
mix-events = { path = "../events" }
mix-exec = { path = "../exec" }
futures-util = { workspace = true }
hyper-util = { version = "0.1.21", features = ["tokio"] }
prost = "0.14.4"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tokio-util = { version = "0.7", default-features = false, features = ["rt"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tower = { version = "0.5.3", features = ["util"] }

[build-dependencies]
protox = "0.9.1"
tonic-prost-build = "0.14.6"

[dev-dependencies]
divan = { workspace = true }
mix-testchild = { path = "../testchild" }

[[bench]]
name = "stream"
harness = false

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]

[lints]
workspace = true
