[package]
name = "mix-core"
version = "0.1.0"
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[features]
model = []

[dependencies]
mix-events = { path = "../events" }
memchr = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
generativity = "1.2.1"

[dev-dependencies]
proptest = { workspace = true }
divan = { workspace = true }
trybuild = "=1.0.121"

[[bench]]
name = "nix_log"
harness = false

[[bench]]
name = "nix_plan"
harness = false

[[bench]]
name = "runner"
harness = false

[[bench]]
name = "state"
harness = false

[[bench]]
name = "targets"
harness = false
