[package]
name = "mix-core"
version = "0.1.0"
edition = "2024"
authors = ["Ömer Tekin"]
license = "MPL-2.0"

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio-util = { version = "0.7", default-features = false }
tracing = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[[bench]]
name = "plan"
harness = false

[[bench]]
name = "plan_observed"
harness = false

[[bench]]
name = "targets"
harness = false
