[package]
name = "mix-nixgen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"
tempfile = "3"

[dependencies.mix-nixgen]
path = ".."

[[bin]]
name = "codegen"
path = "fuzz_targets/codegen.rs"
test = false
doc = false
bench = false

[[bin]]
name = "flake"
path = "fuzz_targets/flake.rs"
test = false
doc = false
bench = false

[workspace]
