[package]
name = "mix-nixgen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"
serde_json = "1"
tempfile = "3"

[dependencies.mix-nixgen]
path = ".."
features = ["parse"]

[[bin]]
name = "attr-path"
path = "fuzz_targets/attr-path.rs"
test = false
doc = false
bench = false

[[bin]]
name = "flake"
path = "fuzz_targets/flake.rs"
test = false
doc = false
bench = false

[[bin]]
name = "home"
path = "fuzz_targets/home.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ident"
path = "fuzz_targets/ident.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[workspace]

[lints.clippy]
disallowed_methods = "allow"
disallowed_macros = "allow"
